name: astrology_ui
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  animate_do: ^4.2.0
  firebase_auth: ^5.4.1
  firebase_core: ^3.10.1
  firebase_storage: ^12.4.4
  cloud_firestore: ^5.6.2
  intl: ^0.20.2
  image_picker: ^1.1.2
  http: ^1.3.0
  connectivity_plus: ^6.1.3
  cupertino_icons: ^1.0.8
  geolocator: ^13.0.3
  flutter_local_notifications: ^19.0.0
  timezone: ^0.10.0
  shared_preferences: ^2.5.2
  flutter_native_splash: ^2.4.4
  shimmer: ^3.0.0
  url_launcher: ^6.1.14
  percent_indicator: ^4.2.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - lib/assets/splash_logo.png
    - lib/assets/app_icon.png
    - lib/assets/zodiac_aries.png
    - lib/assets/zodiac_taurus.png
    - lib/assets/zodiac_gemini.png
    - lib/assets/zodiac_cancer.png
    - lib/assets/zodiac_leo.png
    - lib/assets/zodiac_virgo.png
    - lib/assets/zodiac_libra.png
    - lib/assets/zodiac_scorpio.png
    - lib/assets/zodiac_sagittarius.png
    - lib/assets/zodiac_capricorn.png
    - lib/assets/zodiac_aquarius.png
    - lib/assets/zodiac_pisces.png
    - lib/assets/stars_background.png
    - lib/assets/astro_buddy.png

flutter_native_splash:
  color: "#1E1E2F"
  image: lib/assets/splash_logo.png
  android: true
  ios: false
  android_12:
    image: lib/assets/splash_logo.png
    color: "#1E1E2F"

flutter_icons:
  android: true
  ios: false
  image_path: "lib/assets/app_icon.png"
  adaptive_icon_background: "#1E1E2F"
  adaptive_icon_foreground: "lib/assets/app_icon.png"